# -*- coding: utf-8 -*-
"""question-0002-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cMQ13aKBGv5TrNaXL35KaORXJEuoaDA
"""

import pandas as pd
import numpy as np
import random
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif

# Fijamos semillas para que los resultados sean consistentes durante tus pruebas
np.random.seed(42)
random.seed(42)

def preparar_datos(df: pd.DataFrame,
                   target_col: str,
                   categorias_ordinales: dict,
                   k: int):
    """
    Prepara datos con variables ordinales:
    Codificación -> Selección de k mejores -> Escalado MinMax.
    """
    # 1. Separar X e y (usamos copy para proteger el DataFrame original)
    X = df.drop(columns=[target_col]).copy()
    y = df[target_col].to_numpy(dtype=int)

    # 2. Codificación ordinal preservando el orden lógico definido en el dict
    cols_ordinales = list(categorias_ordinales.keys())
    orden_categorias = [categorias_ordinales[c] for c in cols_ordinales]

    encoder = OrdinalEncoder(categories=orden_categorias)
    X[cols_ordinales] = encoder.fit_transform(X[cols_ordinales])

    # 3. Selección de las k mejores features (basado en ANOVA f_classif)
    # Selecciona las columnas que tienen más relación estadística con el target
    selector = SelectKBest(score_func=f_classif, k=k)
    X_selected = selector.fit_transform(X, y)

    # 4. Normalización al rango [0, 1]
    scaler = MinMaxScaler()
    X_final = scaler.fit_transform(X_selected)

    return X_final, y

# Diccionario maestro de categorías para el simulador
_CATALOGOS_ORDINALES = {
    'acidez': ['baja', 'media', 'alta'],
    'dulzura': ['seco', 'semiseco', 'dulce'],
    'crianza': ['joven', 'roble', 'reserva', 'gran_reserva'],
    'cuerpo': ['ligero', 'medio', 'pleno'],
    'taninos': ['suave', 'moderado', 'astringente'],
}

def generar_caso_de_uso_preparar_datos():
    """
    Genera un caso de prueba aleatorio (input_data, output_esperado).
    """
    n_rows = random.randint(50, 100)
    n_num_features = random.randint(2, 4)

    # Elegir columnas ordinales aleatorias para este caso
    cols_ord_elegidas = random.sample(list(_CATALOGOS_ORDINALES.keys()), k=3)
    n_total_features = n_num_features + len(cols_ord_elegidas)
    k = random.randint(2, n_total_features - 1)

    data = {}
    # Crear features numéricas
    for i in range(n_num_features):
        data[f'feat_num_{i}'] = np.round(np.random.uniform(5.0, 15.0, n_rows), 2)

    # Crear features ordinales
    cat_dict = {}
    for col in cols_ord_elegidas:
        opciones = _CATALOGOS_ORDINALES[col]
        data[col] = np.random.choice(opciones, size=n_rows)
        cat_dict[col] = opciones

    # Target (3 clases de calidad de vino)
    target_col = 'calidad_vino'
    data[target_col] = np.random.randint(0, 3, size=n_rows)

    df = pd.DataFrame(data)

    # --- Cálculo del Ground Truth ---
    X_gt = df.drop(columns=[target_col]).copy()
    y_gt = df[target_col].to_numpy(dtype=int)

    cols_ord = list(cat_dict.keys())
    ord_list = [cat_dict[c] for c in cols_ord]
    X_gt[cols_ord] = OrdinalEncoder(categories=ord_list).fit_transform(X_gt[cols_ord])
    X_sel = SelectKBest(score_func=f_classif, k=k).fit_transform(X_gt, y_gt)
    X_fin = MinMaxScaler().fit_transform(X_sel)

    input_data = {
        'df': df.copy(),
        'target_col': target_col,
        'categorias_ordinales': cat_dict,
        'k': k
    }

    return input_data, (X_fin, y_gt)

if __name__ == "__main__":
    # 1. Generar datos de prueba
    entrada, salida_esperada = generar_caso_de_uso_preparar_datos()

    # 2. Ejecutar tu función
    X_res, y_res = preparar_datos(
        entrada['df'],
        entrada['target_col'],
        entrada['categorias_ordinales'],
        entrada['k']
    )

    # 3. Comparar resultados
    X_gt, y_gt = salida_esperada
    son_iguales = np.allclose(X_res, X_gt, atol=1e-8)

    # 4. Impresión elegante
    print("="*60)
    print("🍷 TEST: PROCESAMIENTO DE DATOS VITIVINÍCOLAS")
    print("="*60)
    print(f"📥 INPUT:")
    print(f"   - Columnas detectadas: {list(entrada['df'].columns)}")
    print(f"   - Valor de k seleccionado: {entrada['k']}")
    print(f"\n📤 OUTPUT:")
    print(f"   - Shape final de X: {X_res.shape}")
    print(f"   - ¿Valores entre 0 y 1?: {X_res.min() >= 0 and X_res.max() <= 1}")
    print(f"\n✅ VEREDICTO: {'¡PRUEBA SUPERADA EXITOSAMENTE!' if son_iguales else 'ERROR EN LA SALIDA'}")
    print("="*60)