# -*- coding: utf-8 -*-
"""question-0001-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vteDsekvaMSew6DNkVTkkcX63Qiy0yl8
"""

import pandas as pd
import numpy as np
import random
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.feature_selection import VarianceThreshold

# Configuramos una semilla para reproducibilidad en pruebas
np.random.seed(42)
random.seed(42)

def preparar_datos(df: pd.DataFrame,
                   target_col: str,
                   grado: int = 2,
                   umbral_varianza: float = 0.01):
    """
    Prepara datos mediante un pipeline: expansión polinomial -> filtro de varianza -> escalado.
    """
    # 1. Separar X e y
    X = df.drop(columns=[target_col])
    y = df[target_col].to_numpy()

    # 2. Construir el Pipeline
    # Usamos include_bias=False porque el StandardScaler se encarga de centrar los datos
    pipeline = Pipeline(steps=[
        ('poly',       PolynomialFeatures(degree=grado, include_bias=False)),
        ('var_filter', VarianceThreshold(threshold=umbral_varianza)),
        ('scaler',     StandardScaler()),
    ])

    # 3. Ajustar y transformar
    X_transformada = pipeline.fit_transform(X)

    return X_transformada, y

def generar_caso_de_uso_preparar_datos():
    """
    Genera un caso de prueba aleatorio (input_data, output_esperado).
    """
    # 1. Configuración aleatoria
    n_rows = random.randint(30, 50)
    n_features = random.randint(2, 4)
    grado = random.choice([2, 3])
    umbral_varianza = round(random.uniform(0.005, 0.02), 4)

    # 2. Generar datos sintéticos
    feature_cols = [f'sensor_{i}' for i in range(n_features)]

    # Creamos datos con escalas muy distintas
    data = np.random.rand(n_rows, n_features) * np.array([100, 1, 10, 50])[:n_features]

    # Forzamos una columna a ser casi constante (ruido mínimo) para que el filtro actúe
    data[:, 0] = 10.0 + np.random.normal(0, 0.001, n_rows)

    df = pd.DataFrame(data, columns=feature_cols)
    target_col = 'output_industrial'
    df[target_col] = np.sin(df[feature_cols[0]]) + np.random.normal(0, 0.1, n_rows)

    # 3. Empaquetar Input
    input_data = {
        'df': df.copy(),
        'target_col': target_col,
        'grado': grado,
        'umbral_varianza': umbral_varianza
    }

    # 4. Calcular Output Esperado (Ground Truth) utilizando la misma lógica
    X_raw = df.drop(columns=[target_col])
    y_raw = df[target_col].to_numpy()

    pipe_gt = Pipeline(steps=[
        ('poly', PolynomialFeatures(degree=grado, include_bias=False)),
        ('var_filter', VarianceThreshold(threshold=umbral_varianza)),
        ('scaler', StandardScaler())
    ])

    X_gt = pipe_gt.fit_transform(X_raw)
    output_esperado = (X_gt, y_raw)

    return input_data, output_esperado

if __name__ == "__main__":
    print("="*60)
    print("🧪 TEST DE VALIDACIÓN: PIPELINE INDUSTRIAL")
    print("="*60)

    # 1. Generar caso
    entrada, salida_esperada = generar_caso_de_uso_preparar_datos()

    print(f"🔹 Parámetros aleatorios:")
    print(f"   - Grado Polinomial: {entrada['grado']}")
    print(f"   - Umbral Varianza:  {entrada['umbral_varianza']}")
    print(f"   - Dimensiones Originales: {entrada['df'].drop(columns=[entrada['target_col']]).shape}")

    # 2. Ejecutar función del estudiante
    X_res, y_res = preparar_datos(
        entrada['df'],
        entrada['target_col'],
        entrada['grado'],
        entrada['umbral_varianza']
    )

    # 3. Validaciones
    X_gt, y_gt = salida_esperada
    check_X = np.allclose(X_res, X_gt, atol=1e-8)
    check_y = np.array_equal(y_res, y_gt)

    print(f"\n📊 RESULTADOS DEL PROCESAMIENTO:")
    print(f"   - Features finales tras el Pipeline: {X_res.shape[1]}")
    print(f"   - Media de X transformada (debe ser ~0): {np.mean(X_res):.4f}")
    print(f"   - Desviación estándar (debe ser ~1): {np.std(X_res):.4f}")

    print(f"\n✅ VERIFICACIÓN FINAL:")
    if check_X and check_y:
        print("   ESTADO: ¡PRUEBA SUPERADA EXITOSAMENTE! 🚀")
    else:
        print("   ESTADO: ❌ ERROR EN LA VALIDACIÓN")

    print("="*60)

