# -*- coding: utf-8 -*-
"""question-0004-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AftnMIFQFSw8jYUGcnx-zHPdukDh8wrI
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import SplineTransformer, FunctionTransformer
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

# Semillas para consistencia
np.random.seed(42)
random.seed(42)

def codificar_ciclico(X_hm: np.ndarray) -> np.ndarray:
    """
    Transforma [hora, mes] en [sin_hora, cos_hora, sin_mes, cos_mes].
    Esto permite que el modelo entienda que las 23h y las 00h son contiguas.
    """
    hora = X_hm[:, 0]
    mes  = X_hm[:, 1]
    return np.column_stack([
        np.sin(2 * np.pi * hora / 24),
        np.cos(2 * np.pi * hora / 24),
        np.sin(2 * np.pi * mes  / 12),
        np.cos(2 * np.pi * mes  / 12),
    ])

def preparar_y_entrenar(df: pd.DataFrame,
                        target_col: str,
                        cols_exogenas: list,
                        n_knots: int = 5) -> dict:
    """
    Realiza ingeniería de variables cíclicas y splines, entrenando un
    modelo que maneja automáticamente la escala logarítmica del target.
    """
    # 1. Preparación de fechas
    df_aux = df.copy()
    df_aux['timestamp'] = pd.to_datetime(df_aux['timestamp'])
    df_aux['hora'] = df_aux['timestamp'].dt.hour.astype(float)
    df_aux['mes']  = df_aux['timestamp'].dt.month.astype(float)

    # 2. Definir matrices X e y
    cols_modelo = cols_exogenas + ['hora', 'mes']
    X = df_aux[cols_modelo].to_numpy(dtype=float)
    y = df_aux[target_col].to_numpy(dtype=float)

    # Índices para el ColumnTransformer
    idx_exog = list(range(len(cols_exogenas)))
    idx_ciclico = [len(cols_exogenas), len(cols_exogenas) + 1]

    # 3. Preprocesador: Splines para clima y Cíclico para tiempo
    preprocesador = ColumnTransformer(transformers=[
        ('spline', SplineTransformer(n_knots=n_knots, degree=3, include_bias=False), idx_exog),
        ('ciclico', FunctionTransformer(func=codificar_ciclico), idx_ciclico),
    ])

    # 4. Split de datos
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 5. Regresor con transformación interna de Target (y -> log(y+1))
    modelo_final = TransformedTargetRegressor(
        regressor=Ridge(alpha=1.0),
        func=np.log1p,
        inverse_func=np.expm1
    )

    # Ajustar preprocesador y entrenar modelo
    X_train_prep = preprocesador.fit_transform(X_train)
    modelo_final.fit(X_train_prep, y_train)

    # 6. Evaluación
    X_test_prep = preprocesador.transform(X_test)
    y_pred = modelo_final.predict(X_test_prep)

    return {
        'mae': float(mean_absolute_error(y_test, y_pred)),
        'r2': float(r2_score(y_test, y_pred)),
        'modelo': modelo_final,
        'prep': preprocesador
    }

def generar_caso_de_uso_preparar_datos():
    """
    Genera un dataset de consumo eléctrico con estacionalidad horaria.
    """
    n_rows = random.randint(400, 600)
    n_knots = 5

    # Generar Timestamps
    inicio = datetime(2023, 1, 1)
    timestamps = [inicio + timedelta(hours=i) for i in range(n_rows)]

    # Features climáticas aleatorias
    cols_exog = ['temp_ambiente', 'humedad']
    data = {
        'timestamp': timestamps,
        'temp_ambiente': np.random.uniform(10, 35, n_rows),
        'humedad': np.random.uniform(30, 90, n_rows)
    }

    # Target con patrón de consumo (más alto al mediodía y noche)
    hrs = np.array([t.hour for t in timestamps])
    patron = 100 + 50 * np.sin(2 * np.pi * hrs / 24) + 20 * np.random.randn(n_rows)
    data['consumo_kwh'] = np.abs(patron) + 10 # Asegurar positivos para log

    df = pd.DataFrame(data)

    # Obtener el Ground Truth ejecutando la función solución
    gt_res = preparar_y_entrenar(df.copy(), 'consumo_kwh', cols_exog, n_knots)

    input_data = {
        'df': df,
        'target_col': 'consumo_kwh',
        'cols_exogenas': cols_exog,
        'n_knots': n_knots
    }

    output_esperado = {'mae': gt_res['mae'], 'r2': gt_res['r2']}

    return input_data, output_esperado

if __name__ == "__main__":
    # 1. Generar caso
    entrada, salida_esp = generar_caso_de_uso_preparar_datos()

    # 2. Ejecutar función del estudiante
    res = preparar_y_entrenar(**entrada)

    # 3. Verificación numérica
    mae_diff = abs(res['mae'] - salida_esp['mae'])
    r2_diff = abs(res['r2'] - salida_esp['r2'])

    print("="*70)
    print("⚡ TEST: PREDICCIÓN DE DEMANDA ENERGÉTICA (RECURSIVO)")
    print("="*70)
    print(f"📊 Métricas Obtenidas:")
    print(f"   - MAE: {res['mae']:.4f} kWh")
    print(f"   - R²:  {res['r2']:.4f}")

    if mae_diff < 1e-6 and r2_diff < 1e-6:
        print("\n✅ ¡EXCELENTE! El modelo y el preprocesamiento coinciden exactamente.")
    else:
        print("\n❌ ERROR: Hay una discrepancia en los cálculos del modelo.")
    print("="*70)