# -*- coding: utf-8 -*-
"""question-0003-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5qMPXKlof20ic9RW03S1sFKlCnwJdYH
"""

import pandas as pd
import numpy as np
import random
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import IsolationForest

# Configuración de reproducibilidad
np.random.seed(42)
random.seed(42)

def preparar_datos(df: pd.DataFrame,
                   target_col: str,
                   cols_numericas: list,
                   cols_categoricas: list,
                   contaminacion: float = 0.05):
    """
    Preprocesa solicitudes de crédito (mixtas) y elimina anomalías.
    """
    # 1. Separar X e y
    X = df[cols_numericas + cols_categoricas].copy()
    y = df[target_col].to_numpy()

    # 2. ColumnTransformer: Ramas paralelas para numéricas y categóricas
    rama_numerica = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler',  StandardScaler()),
    ])

    rama_categorica = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='constant', fill_value='desconocido')),
        ('onehot',  OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
    ])

    preprocesador = ColumnTransformer(transformers=[
        ('numerica',   rama_numerica,   cols_numericas),
        ('categorica', rama_categorica, cols_categoricas),
    ])

    # Aplicar transformaciones
    X_prep = preprocesador.fit_transform(X)

    # 3. IsolationForest: Detectar y eliminar filas anómalas
    # random_state=42 asegura que el resultado sea reproducible para el test
    iso = IsolationForest(contamination=contaminacion, random_state=42)
    mascara = iso.fit_predict(X_prep)          # +1 normal, -1 anomalía

    # Filtrar solo las filas normales
    filas_normales = (mascara == 1)
    X_limpio = X_prep[filas_normales]
    y_limpio = y[filas_normales]

    return X_limpio, y_limpio

_TIPOS_EMPLEO   = ['formal', 'independiente', 'desempleado']
_NIVELES_ESTUDIO = ['primaria', 'secundaria', 'universitario', 'posgrado']

def generar_caso_de_uso_preparar_datos():
    """
    Genera un caso de prueba aleatorio (input_data, output_esperado).
    """
    n_rows = random.randint(100, 200)
    contaminacion = round(random.uniform(0.05, 0.1), 3)

    # Selección aleatoria de columnas para el caso
    todas_num = ['ingresos', 'deuda', 'score_crediticio', 'edad']
    cols_numericas = random.sample(todas_num, k=3)
    cols_categoricas = ['tipo_empleo', 'nivel_estudio']

    data = {}
    # Generar numéricas con algunos NaNs
    for col in cols_numericas:
        vals = np.random.uniform(1000, 10000, n_rows)
        vals[np.random.choice([True, False], size=n_rows, p=[0.1, 0.9])] = np.nan
        data[col] = vals

    # Generar categóricas
    data['tipo_empleo'] = np.random.choice(_TIPOS_EMPLEO, size=n_rows)
    data['nivel_estudio'] = np.random.choice(_NIVELES_ESTUDIO, size=n_rows)

    # Target
    target_col = 'riesgo_impago'
    data[target_col] = np.random.randint(0, 2, size=n_rows)

    df = pd.DataFrame(data)

    # --- Cálculo del Ground Truth (Lógica idéntica a la función) ---
    # Se repite internamente para comparar resultados
    X_raw = df[cols_numericas + cols_categoricas].copy()
    y_raw = df[target_col].to_numpy()

    p_num = Pipeline([('i', SimpleImputer(strategy='median')), ('s', StandardScaler())])
    p_cat = Pipeline([('i', SimpleImputer(strategy='constant', fill_value='desconocido')),
                      ('o', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

    ct = ColumnTransformer([('n', p_num, cols_numericas), ('c', p_cat, cols_categoricas)])
    X_p = ct.fit_transform(X_raw)

    mask = IsolationForest(contamination=contaminacion, random_state=42).fit_predict(X_p)
    X_exp, y_exp = X_p[mask == 1], y_raw[mask == 1]

    input_data = {
        'df': df.copy(),
        'target_col': target_col,
        'cols_numericas': cols_numericas,
        'cols_categoricas': cols_categoricas,
        'contaminacion': contaminacion
    }

    return input_data, (X_exp, y_exp)

if __name__ == "__main__":
    # 1. Obtener caso aleatorio
    entrada, salida_esperada = generar_caso_de_uso_preparar_datos()

    # 2. Ejecutar función del estudiante
    X_res, y_res = preparar_datos(**entrada)

    # 3. Validar contra Ground Truth
    X_gt, y_gt = salida_esperada
    coinciden = np.allclose(X_res, X_gt, atol=1e-8)

    # 4. Reporte
    print("="*65)
    print("🏦 TEST: SISTEMA DE CRÉDITO (BANCARIO)")
    print("="*65)
    print(f"📥 RESUMEN DE ENTRADA:")
    print(f"   - Registros iniciales: {entrada['df'].shape[0]}")
    print(f"   - Contaminación (Outliers): {entrada['contaminacion']:.1%}")
    print(f"\n📤 RESULTADO DEL PROCESAMIENTO:")
    print(f"   - Registros finales (limpios): {X_res.shape[0]}")
    print(f"   - Registros eliminados por anomalía: {entrada['df'].shape[0] - X_res.shape[0]}")
    print(f"   - Total de features (tras OneHot): {X_res.shape[1]}")

    if coinciden:
        print("\n✅ VEREDICTO: ¡PRUEBA PASADA! Los datos están correctamente preprocesados.")
    else:
        print("\n❌ VEREDICTO: ERROR. Los datos procesados no coinciden con el estándar.")
    print("="*65)